layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Virtualization
    web_url: https://www.docker.com/
    image_url: https://www.docker.com/sites/default/files/social/docker_facebook_share.png

  - name: Capture the Flag Challenges
    web_url: https://www.vulnhub.com/
    image_url: https://hackt.nl/wp-content/uploads/2018/09/vulnhub-702x336.png

  - name: Cyber Security
    web_url: https://www.cybrary.it/
    image_url: https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTpdD3MKVKO6qfGY0uXFK9GIAAz0ulN14B3CwwVkUdmBODNitpo
